language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
     - pip install -U platformio
     - platformio update
     - echo "const char *ssid = \"\";" > src/secrets.h
     - echo "const char *password = \"\";" >> src/secrets.h
     - echo "const String serverUrl = \"\";" >> src/secrets.h

script:
    - platformio run